export const STATUS_CONDITIONS = Object.freeze([
    // وضعیت‌های منفی و ناتوان‌کننده
    {
        id: "incapacitated",
        name: "Incapacitated",
        nameFa: "ناتوان / از کار افتاده",
        icon: "💫",
        badgeColor: "#9333ea",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-purple-600 border-purple-400 text-white",
        category: "harmful",
        descriptionFa: "قادر به انجام هیچ اکشن یا ری‌اکشنی نیست.",
    },
    {
        id: "prone",
        name: "Prone",
        nameFa: "افتاده بر زمین (Prone)",
        icon: "🧎",
        badgeColor: "#ea580c",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-orange-600 border-orange-400 text-white",
        category: "movement",
        descriptionFa: "روی زمین افتاده؛ حملات نزدیک علیه او ادونتیج دارند.",
    },
    {
        id: "invisible",
        name: "Invisible",
        nameFa: "نامرئی (Invisible)",
        icon: "👻",
        badgeColor: "#0284c7",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-sky-600 border-sky-400 text-white",
        category: "sensory",
        descriptionFa: "بدون جادو یا حس‌های خاص دیده نمی‌شود؛ حملات او ادونتیج دارند.",
    },
    {
        id: "unconscious",
        name: "Unconscious",
        nameFa: "بیهوش (Unconscious)",
        icon: "💤",
        badgeColor: "#be123c",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-rose-700 border-rose-500 text-white",
        category: "harmful",
        descriptionFa: "کاملاً بیهوش و ناتوان؛ تمامی حملات نزدیک به او کریتیکال می‌شوند.",
    },
    {
        id: "paralyzed",
        name: "Paralyzed",
        nameFa: "فلج شده (Paralyzed)",
        icon: "⚡",
        badgeColor: "#d97706",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-amber-600 border-amber-400 text-white",
        category: "harmful",
        descriptionFa: "قادر به حرکت و صحبت نیست؛ به طور خودکار سیوینگ ترو‌های استرنگت و دکستریتی را فیل می‌کند.",
    },
    {
        id: "poisoned",
        name: "Poisoned",
        nameFa: "مسموم (Poisoned)",
        icon: "🧪",
        badgeColor: "#059669",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-emerald-600 border-emerald-400 text-white",
        category: "harmful",
        descriptionFa: "در تاس‌های حمله و چک‌های ابیلیتی دیس‌ادونتیج دارد.",
    },
    {
        id: "blinded",
        name: "Blinded",
        nameFa: "کور شده (Blinded)",
        icon: "🙈",
        badgeColor: "#4b5563",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-zinc-600 border-zinc-400 text-white",
        category: "sensory",
        descriptionFa: "جایی را نمی‌بیند؛ چک‌های بینایی فیل و حملات او دیس‌ادونتیج دارند.",
    },
    {
        id: "frightened",
        name: "Frightened",
        nameFa: "وحشت‌زده (Frightened)",
        icon: "😱",
        badgeColor: "#7c3aed",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-violet-600 border-violet-400 text-white",
        category: "mental",
        descriptionFa: "نمی‌تواند به منبع ترس نزدیک شود و تاس‌هایش دیس‌ادونتیج دارند.",
    },
    {
        id: "charmed",
        name: "Charmed",
        nameFa: "افسون شده (Charmed)",
        icon: "💖",
        badgeColor: "#db2777",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-pink-600 border-pink-400 text-white",
        category: "mental",
        descriptionFa: "نمی‌تواند به افسون‌کننده حمله کند و او در تعاملات ادونتیج دارد.",
    },
    {
        id: "stunned",
        name: "Stunned",
        nameFa: "گیج شده (Stunned)",
        icon: "🌀",
        badgeColor: "#ca8a04",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-yellow-600 border-yellow-400 text-white",
        category: "harmful",
        descriptionFa: "ناتوان، لکنتی و ناتوان در حرکت؛ حملات علیه او ادونتیج دارند.",
    },
    {
        id: "restrained",
        name: "Restrained",
        nameFa: "در بند / بسته شده (Restrained)",
        icon: "⛓️",
        badgeColor: "#475569",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-slate-600 border-slate-400 text-white",
        category: "movement",
        descriptionFa: "سرعت حرکت ۰ است و در تاس‌های حمله دیس‌ادونتیج دارد.",
    },
    {
        id: "deafened",
        name: "Deafened",
        nameFa: "ناشنوا (Deafened)",
        icon: "🔇",
        badgeColor: "#64748b",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-slate-500 border-slate-300 text-white",
        category: "sensory",
        descriptionFa: "صدایی نمی‌شنود و چک‌های وابسته به شنوایی فیل می‌شوند.",
    },
    {
        id: "burning",
        name: "Burning",
        nameFa: "آتش گرفته (Burning)",
        icon: "🔥",
        badgeColor: "#dc2626",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-red-600 border-red-400 text-white",
        category: "harmful",
        descriptionFa: "در ابتدای هر راند آسیب آتشین دریافت می‌کند.",
    },
    {
        id: "bleeding",
        name: "Bleeding",
        nameFa: "خونریزی (Bleeding)",
        icon: "🩸",
        badgeColor: "#991b1b",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-rose-800 border-rose-600 text-white",
        category: "harmful",
        descriptionFa: "به ازای هر حرکت یا پایان نوبت جان از دست می‌دهد.",
    },

    // وضعیت‌های مثبت (Buffs)
    {
        id: "blessed",
        name: "Blessed",
        nameFa: "متبرک (Blessed)",
        icon: "✨",
        badgeColor: "#f59e0b",
        badgeTextColor: "#000000",
        tailwindClass: "bg-amber-400 border-amber-200 text-zinc-950 font-bold",
        category: "buff",
        descriptionFa: "+1d4 به تمام تاس‌های حمله و سیوینگ تروها اضافه می‌شود.",
    },
    {
        id: "hasted",
        name: "Hasted",
        nameFa: "شتاب‌یافته (Hasted)",
        icon: "⚡",
        badgeColor: "#06b6d4",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-cyan-600 border-cyan-400 text-white",
        category: "buff",
        descriptionFa: "سرعت دو برابر، +2 به AC، ادونتیج در دکستریتی و یک اکشن اضافه در نوبت.",
    },
    {
        id: "concentrating",
        name: "Concentrating",
        nameFa: "تمرکز جادو (Concentration)",
        icon: "🔮",
        badgeColor: "#8b5cf6",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-purple-500 border-purple-300 text-white",
        category: "buff",
        descriptionFa: "در حال حفظ تمرکز روی یک اسپل فعال؛ در صورت دریافت آسیب نیاز به Con Save دارد.",
    },
    {
        id: "shielded",
        name: "Shielded",
        nameFa: "سپر محافظ جادویی (Shielded)",
        icon: "🛡️",
        badgeColor: "#3b82f6",
        badgeTextColor: "#ffffff",
        tailwindClass: "bg-blue-600 border-blue-400 text-white",
        category: "buff",
        descriptionFa: "سپر جادویی فعال برای دفع حملات فیزیکی یا جادویی.",
    },
]);

export const CONDITION_MAP = Object.freeze(
    STATUS_CONDITIONS.reduce((acc, cond) => {
        acc[cond.id] = cond;
        return acc;
    }, {})
);