export const TOKEN_PRESETS = [
  {
    id: "preset-warrior",
    name: "Sir Gareth (Paladin)",
    nameFa: "شوالیه گارث (پالادین)",
    category: "heroes",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Gareth&backgroundColor=b6e3f4",
    size: 1,
    color: "#3b82f6",
    maxHp: 42,
    ac: 18,
    speed: 30,
  },
  {
    id: "preset-wizard",
    name: "Elara the Arcane (Mage)",
    nameFa: "الارا جادوگر (میج)",
    category: "heroes",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Elara&backgroundColor=c0aede",
    size: 1,
    color: "#8b5cf6",
    maxHp: 26,
    ac: 13,
    speed: 30,
  },
  {
    id: "preset-rogue",
    name: "Vaelin Shadowstep (Rogue)",
    nameFa: "ولین سایه‌رو (روگ)",
    category: "heroes",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Vaelin&backgroundColor=ffd5dc",
    size: 1,
    color: "#10b981",
    maxHp: 31,
    ac: 15,
    speed: 35,
  },
  {
    id: "preset-cleric",
    name: "Father Kaelen (Cleric)",
    nameFa: "پدر کالن (کلریک)",
    category: "heroes",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Kaelen&backgroundColor=ffdfbf",
    size: 1,
    color: "#f59e0b",
    maxHp: 38,
    ac: 17,
    speed: 30,
  },
  {
    id: "preset-goblin",
    name: "Goblin Raider",
    nameFa: "مهاجم گابلین",
    category: "monsters",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Goblin1&backgroundColor=d1fae5",
    size: 1,
    color: "#ef4444",
    maxHp: 7,
    ac: 15,
    speed: 30,
  },
  {
    id: "preset-orc",
    name: "Orc Warchief",
    nameFa: "سرکرده اورک‌ها",
    category: "monsters",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=OrcWar&backgroundColor=fee2e2",
    size: 1,
    color: "#dc2626",
    maxHp: 45,
    ac: 16,
    speed: 30,
  },
  {
    id: "preset-red-dragon",
    name: "Adult Red Dragon",
    nameFa: "اژدهای سرخ باستانی",
    category: "monsters",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=RedDragon&backgroundColor=f87171",
    size: 3,
    color: "#b91c1c",
    maxHp: 256,
    ac: 19,
    speed: 80,
  },
  {
    id: "preset-skeleton",
    name: "Skeleton Archer",
    nameFa: "کماندار اسکلت",
    category: "monsters",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Skeleton&backgroundColor=e5e7eb",
    size: 1,
    color: "#9ca3af",
    maxHp: 13,
    ac: 13,
    speed: 30,
  },
  {
    id: "preset-innkeeper",
    name: "Tavern Keeper Boros",
    nameFa: "صاحب‌کاروانسرای بوروس",
    category: "npcs",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Boros&backgroundColor=fef3c7",
    size: 1,
    color: "#d97706",
    maxHp: 20,
    ac: 10,
    speed: 30,
  },
  {
    id: "preset-chest",
    name: "Treasure Chest",
    nameFa: "صندوقچه گنج طلا",
    category: "props",
    avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=Chest&backgroundColor=fef08a",
    size: 1,
    color: "#eab308",
    maxHp: 50,
    ac: 15,
    speed: 0,
  },
];