/**
 * رویدادهای استاندارد وب‌سوکت کلاینت و سرور
 * طبق بند عدم تغییر اسامی رویدادها در سند
 */
export const WS_EVENTS = Object.freeze({
    TOKEN_MOVED: "TOKEN_MOVED",
    TOKEN_CREATED: "TOKEN_CREATED",
    TOKEN_UPDATED: "TOKEN_UPDATED",
    TOKEN_DELETED: "TOKEN_DELETED",
    FOG_UPDATED: "FOG_UPDATED",
    DRAWING_ADDED: "DRAWING_ADDED",
    DRAWING_DELETED: "DRAWING_DELETED",
    DRAWINGS_CLEARED: "DRAWINGS_CLEARED",
    VIEWPORT_SYNC: "VIEWPORT_SYNC",
    MEMBER_MUTE_TOGGLED: "MEMBER_MUTE_TOGGLED",
    ROLE_TITLE_UPDATE: "ROLE_TITLE_UPDATE",
    SCENE_ACTIVATED: "SCENE_ACTIVATED",
    SCENE_UPDATED: "SCENE_UPDATED",
    PING_EMITTED: "PING_EMITTED",
    MEMBER_JOINED: "MEMBER_JOINED",
    MEMBER_LEFT: "MEMBER_LEFT",
    MEMBER_KICKED: "MEMBER_KICKED",
    MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
    SETTINGS_UPDATED: "SETTINGS_UPDATED",
});